Repository BF-FrontEnd-class-2024/Group3-HYF-rebuild, pull requests merged in 2024-01, with the labels that each got.

#2 add constraints
  planning/constraints.md
Labels: md

#4 add communication file
  .cspell.json
  planning/communication.md
Labels: md

#6 update main readme file
  README.md
Labels: md

#8 add user persona file
  .cspell.json
  planning/user-personas.md
Labels: md

#10 add backlog-file
  .cspell.json
  planning/backlog.md
Labels: md

#12 Add dev strategy
  planning/development-strategy.md
Labels: md

#14 add design file
  img/home.png
  planning/design.md
Labels: md

#16 setup pages
  .cspell.json
  pages/about.html
  pages/program.html
  pages/volunteer.html
  styles/about.css
  styles/index.css
  styles/program.css
  styles/volunteer.css
Labels: html, css

#28 program.html page
  .cspell.json
  img/css.webp
  img/html.webp
  img/hyfbe.webp
  img/js.webp
  img/mysql.webp
  img/nodejs.webp
  img/react.webp
  pages/program.html
  styles/program.css
Labels: html, css

#30 updated the html and css file of the program page
  img/facebook.png
  img/github.png
  img/instagram.png
  img/linkedin.png
  pages/program.html
  styles/program.css
Labels: html, css

#32 updated the html files of the program page
  pages/program.html
Labels: html

#35 add a volunteer page
  .cspell.json
  img/anthony.webp
  img/eleni.webp
  img/hyf.webp
  img/hyf2.png
  img/img3.webp
  img/img4.webp
  img/img5.webp
  img/img6.webp
  img/jonathan.webp
  pages/volunteer.html
  styles/volunteer.css
Labels: html, css

#33 added Html and css for About page
  .cspell.json
  img/a network.webp
  img/dedicat.webp
  img/facebook.webp
  img/family em.webp
  img/github.webp
  img/hack ur f image.webp
  img/hyf imag4.webp
  img/hyf image 2.webp
  img/hyf image 3.webp
  img/hyf image.webp
  img/hyf main ima.webp
  img/hyf.png
  img/insta.webp
  img/linkedin.webp
  img/mission.webp
  img/passion.webp
  img/vision.webp
  img/volunteers.png
  pages/about.html
  pages/another-page.html
  styles/about.css
Labels: html, css
